development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

demo:
  adapter: sqlite3
  database: db/demo.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: postgres
  database: coyoho
  username: coyoho
  password: coyoho
  encoding: unicode
  pool: 5
  timeout: 5000
