development:
  adapter: sqlite3
  database: db/sqlite/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/sqlite/test.sqlite3
  pool: 5
  timeout: 5000

demo:
  adapter: sqlite3
  database: db/sqlite/demo.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/sqlite/production.sqlite3
  pool: 5
  timeout: 5000
