development:
  sessions:
    default:
      database: coyoho
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: coyoho-test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: coyoho
      hosts:
        - localhost:27017
