<% require 'socket' %>

network:
  broadcast_port: 55555
  public_ip: '<%= IPSocket.getaddress(Socket.gethostname) %>'
websocket:
  standalone: false
  url: '<%= IPSocket.getaddress(Socket.gethostname) %>:3000/websocket'
