network:
  broadcast_port: 55555
  public_ip: <%= ENV['CARETAKER_PUBLIC_IP'] %>
  device_ip: <%= ENV['CARETAKER_DEVICE_IP'] %>
websocket:
  standalone: false
  url: "<%= ENV['CARETAKER_PUBLIC_IP'] %>:3000/websocket"
