network:
  broadcast_port: 55555
  public_ip: <%= ENV['CARETAKER_PUBLIC_IP'] %>
  device_ip: <%= ENV['CARETAKER_DEVICE_IP'] %>
  api_url: <%= ENV['CARETAKER_API_URL'] %>
websocket:
  standalone: false
  url: "<%= ENV['CARETAKER_WEBSOCKET_HOST'] %>:<%= ENV['CARETAKER_WEBSOCKET_PORT'] %>/websocket"
