network:
  broadcast_port: 55555
  public_ip: <%= ENV['RAILS_PUBLIC_IP'] %>
  device_ip: <%= ENV['RAILS_DEVICE_IP'] %>
websocket:
  standalone: false
  url: "<%= ENV['RAILS_PUBLIC_IP'] %>:3000/websocket"
